package: nb_anacondacloud

platform:
  - linux-64
  - linux-32
  - osx-64
  - win-64
  - win-32

engine:
  - python=2.7
  - python=3.4
  - python=3.5

install:
  - conda build conda.recipe -c anaconda-notebook -c javascript -c mutirri -c jakirkham -c bokeh
  - conda install nb_anacondacloud --use-local -c anaconda-notebook

build_targets: conda
