# This file declares this nbextension to the jupyter_nbextensions_configurator.
# See
#     https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator
# for further details.
Type: Jupyter Notebook Extension
Name: Anaconda Cloud
Description: |
  Interact with Anaconda Cloud from the notebook.
  Adds a toolbar button to upload notebooks to Anaconda Cloud.
Main: main.js
Compatibility: 4.x
Link: https://github.com/Anaconda-Platform/nb_anacondacloud
