package:
  name: nb_anacondacloud
  version: 0.1.0

requirements:
  build:
    - anaconda-client
    - nbsetuptools
    - python
    - setuptools
  run:
    - anaconda-client
    - nbsetuptools
    - notebook

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/nb_anacondacloud
  license: BSD
