package:
  name: nb_anacondacloud
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

requirements:
  build:
    - anaconda-client
    - python 2.7*|3.4*|3.5*
    - setuptools
    - notebook >=4.2.0
  run:
    - anaconda-client
    - notebook >=4.2.0
    - pyyaml
    - python

test:
  files:
    - package.json
    - setup.cfg
  requires:
    - anaconda-client
    - coverage
    - flake8
    - freetype
    - funcsigs
    - nodejs
    - nose
    - notebook >=4.2.0
    - python 2.7*|3.4*|3.5*
    - pyyaml
    - requests
    - fontconfig # [linux]
    - mock # [py2k]

about:
  home: https://github.com/Anaconda-Platform/nb_anacondacloud
  license: BSD
