package:
  name: nb_anacondacloud
  version: 0.1.2

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}{{ environ.get('PY_VER').replace('.', '') }}_0{% else %}{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

requirements:
  build:
    - anaconda-client
    - python
    - setuptools
  run:
    - anaconda-client
    - notebook ==5.0.0
    - pyyaml
    - python

test:
  files:
    - package.json
  requires:
    - anaconda-client
    - coverage
    - flake8
    - freetype
    - funcsigs
    - mock
    - nodejs
    - nose
    - notebook
    - python
    - pyyaml
    - requests
    - npm # [linux32]
    - npm # [win]
    - fontconfig [linux]

source:
  path: ../

about:
  home: https://github.com/Anaconda-Server/nb_anacondacloud
  license: BSD
