package:
  name: nb_anacondacloud
  version: 0.2.0

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

requirements:
  build:
    - anaconda-client
    - python
    - setuptools
  run:
    - anaconda-client
    - notebook
    - pyyaml
    - python

test:
  files:
    - package.json
  requires:
    - anaconda-client
    - coverage
    - flake8
    - freetype
    - funcsigs
    - mock
    - nodejs
    - nose
    - notebook
    - python
    - pyyaml
    - requests
    - npm # [linux32]
    - npm # [win]
    - fontconfig [linux]

about:
  home: https://github.com/Anaconda-Server/nb_anacondacloud
  license: BSD
